#!/bin/bash

# if this is first run, /etc/xsce/config_vars.yml will not exist
if [ ! -f /etc/xsce/config_vars.yml ];then
   mkdir -p /etc/xsce
   echo "{}" > /etc/xsce/config_vars.yml
fi

# if this script is running from a non standard place, record in xsce.env
CWD=$( dirname $( readlink -f $0 ) )
if [ "$CWD" != "/opt/schoolserver/xsce" ] && [ ! -f /etc/xsce/xsce.env ];then
   # we need a xcse.env to keep things straight
   mkdir -p /etc/xsce
   echo "XSCE_DIR=$CWD" >> /etc/xsce/xsce.env
fi

if [ -f /etc/xsce/xsce.env ]
then
  . /etc/xsce/xsce.env
  cd $XSCE_DIR
fi

PLAYBOOK="xsce-base.yml"
INVENTORY="ansible_hosts"
SELINUX_BEFORE=""
SELINUX_AFTER=""

if [ ! -f $PLAYBOOK ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit 1
fi

if [ -f /etc/selinux/config ]
then
 SELINUX_BEFORE=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`
fi

export ANSIBLE_LOG_PATH="$XSCE_DIR/xsce-install.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local

if [ -f /etc/selinux/config ]
then
 SELINUX_AFTER=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`
fi

if [ "$SELINUX_BEFORE" != "$SELINUX_AFTER" ]; then
  echo "Rebooting ..."
  reboot
fi
